### ISSUE TITLE
codon-variant table missing

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/SARS-CoV-2-RBD_B.1.351#27]
@ajgreaney, the codon variant table linked to in the summary is still missing. I wonder if problem is that it's not in your `.gitignore`?

**Comment by ajgreaney** [comment]
Yes, I'm working on it. I haven't pushed any changes yet because I have been trying to add the latest run of sequencing data so all the output files downstream of `count_variants` have been changed, but I am also running into some problem. I will definitely resolve this soon.

**Comment by ajgreaney** [comment]
fixed in #29
